export const posts = [
  {
    name: 'Alice S.',
    title: 'INVASION OF ZOMBIES AT THE STATION OF KORTIJK!',
    avatar: require('../assets/img/avatars/1.png'),
    location: 'Kortrijk',
    content: " — Be careful, if you're nearby.",
    online: true,
  },
  {
    name: 'Bob Jey.',
    title: 'HELP!!!',
    avatar: require('../assets/img/avatars/2.png'),
    location: 'Charleroi',
    content: " — My little girl is trapped under a train, and I can't go rescue her!",
    online: false,
  },
  {
    name: 'Sam Nadji',
    title: 'NECESSITY OF FOOD SUPPLY',
    avatar: require('../assets/img/avatars/3.png'),
    location: 'Liege',
    content: ' — I have no more food for me and my family, I need supplies, as soon as possible.',
    online: false,
  },
  {
    name: 'Cedric Adil.',
    title: 'I CAN HELP!!!',
    avatar: require('../assets/img/avatars/4.png'),
    location: 'Brussels',
    content:
      " — I'm in a non-contaminated area, I have a roof and food for those in the vicinity...",
    online: true,
  },
  {
    name: 'Bob Sery.',
    title: 'I NEED A DOCTOR',
    avatar: require('../assets/img/avatars/5.png'),
    location: 'Mons',
    content: ' — I have to have an arm amputated as soon as possible, a doctor around? Please.',
    online: false,
  },
  {
    name: 'Alice A.',
    title: 'HEEEY',
    avatar: require('../assets/img/avatars/6.png'),
    location: 'Brussels',
    content: " — Wish I couldasda, but I'm out of town this…",
    online: false,
  },
  {
    name: 'Alice A.',
    title: 'HEEEY',
    avatar: require('../assets/img/avatars/7.png'),
    location: 'Brussels',
    content: " — Wish I couldasda, but I'm out of town this…",
    online: true,
  },
  {
    name: 'Alice A.',
    title: 'HEEEY',
    avatar: require('../assets/img/avatars/8.png'),
    location: 'Brussels',
    content: " — Wish I couldasda, but I'm out of town this…",
    online: true,
  },
  {
    name: 'Alice A.',
    title: 'HEEEY',
    avatar: require('../assets/img/avatars/9.png'),
    location: 'Brussels',
    content: " — Wish I couldasda, but I'm out of town this…",
    online: false,
  },
  {
    name: 'Alice A.',
    title: 'HEEEY',
    avatar: require('../assets/img/avatars/10.png'),
    location: 'Brussels',
    content: " — Wish I couldasda, but I'm out of town this…",
    online: false,
  },
];
