export const posts = [
  {
    name: 'Alice S.',
    title: 'INVASION OF ZOMBIES AT THE STATION OF KORTIJK!',
    avatar: require('../assets/img/avatars/1.png'),
    location: 'Kortrijk',
    content: " — Be careful, if you're nearby.",
    online: true,
  },
  {
    name: 'Bob Jey.',
    title: 'HELP!!!',
    avatar: require('../assets/img/avatars/2.png'),
    location: 'Charleroi',
    content: " — My little girl is trapped under a train, and I can't go rescue her!",
    online: false,
  },
  {
    name: 'Sam Nadji',
    title: 'NECESSITY OF FOOD SUPPLY',
    avatar: require('../assets/img/avatars/3.png'),
    location: 'Liege',
    content: ' — I have no more food for me and my family, I need supplies, as soon as possible.',
    online: false,
  },
  {
    name: 'Cedric Adil.',
    title: 'I CAN HELP!!!',
    avatar: require('../assets/img/avatars/4.png'),
    location: 'Brussels',
    content:
      " — I'm in a non-contaminated area, I have a roof and food for those in the vicinity...",
    online: true,
  },
  {
    name: 'Bob Sery.',
    title: 'I NEED A DOCTOR',
    avatar: require('../assets/img/avatars/5.png'),
    location: 'Mons',
    content: ' — I have to have an arm amputated as soon as possible, a doctor around? Please.',
    online: true,
  },
  {
    name: 'Dirk Opaz.',
    title: "I'VE GOT GUNS AND AMMUNITION. I CAN HELP PROTECT YOU",
    avatar: require('../assets/img/avatars/6.png'),
    location: 'Namur',
    content: " — If you're in the vicinity of jemappe, contact me, I can help you. Don't be alone!",
    online: false,
  },
  {
    name: 'Fatima',
    title: 'MY FAMILY IS GONE',
    avatar: require('../assets/img/avatars/7.png'),
    location: 'Roeulx',
    content: " — I'd give anything to find them, that's all I have left!",
    online: true,
  },
  {
    name: 'Erik Stone',
    title: 'ZOMBIES IN CHARLEROI!!!!',
    avatar: require('../assets/img/avatars/8.png'),
    location: 'Dinan',
    content: ' — I saw a zombie cluster of over 500 zombies on the Boulevard Tirou square!',
    online: true,
  },
  {
    name: 'Alice A.',
    title: "I'M THIRSTY, COLD AND HUNGRY",
    avatar: require('../assets/img/avatars/9.png'),
    location: 'Tournai',
    content: " — All I'm asking for is a sip of water, a piece of meat, please...",
    online: false,
  },
  {
    name: 'Alice Osera',
    title: 'I LOST MY MOM!!!',
    avatar: require('../assets/img/avatars/10.png'),
    location: 'Marche-en-Famenne',
    content: " — Do you have a car to help me find her? I'd be most grateful.",
    online: false,
  },
];
